### ISSUE TITLE
window expansion when initialised

### ISSUE THREAD

**Issue by dietcv** [madskjeldgaard/nodeproxygui2#55]
hey, would it be possible that the window expands to its fullest when initialised to show all the params possible before scrolling takes over? Otherwise you always have to manually expand the window.

see the example below:

(
Ndef(\test, {
	var freqRange = \freqRange.kr(Array.fill(20, {440}), spec: ControlSpec(20, 1000));
}).gui2;
)

**Comment by redFrik** [comment]
at the moment, the logic is that when there are more parameters than can fit the space of half the display's height, the window is shrunk and made scrollable.

see line 378 in NodeProxyGui2.sc...
```
if(parameterSection.bounds.height > (Window.availableBounds.height * 0.5), {
	parameterSection = ScrollView.new().canvas_(parameterSection);
```

so you're proposing to use `* 1.0` here instead of `* 0.5`?
i guess that would work, but i don't remember why we wrote it like this.  would full height cause trouble for tiled window managers?
or maybe this should be exposed as a settable classvar (numParamsBeforeScroll)?

**Comment by salkin-mada** [comment]
Hmm I don't think this `0.5` is related to tiling wm's having issue will full height. But I could be wrong.. maybe some QT—Wayland friendship trouble. Will check on the Sway SBC at work in the morning.

**Comment by salkin-mada** [comment]
Ah I see. Its a hack, a really brute approximation of transportSection and infoSection..
```supercollider
parameterSection.bounds.height > Window.availableBounds.height
```
Is not taking into account the size of the window, border, menu, and sections. So therefor some lazy programmer just did `(Window.availableBounds.height * 0.5)` 😀
I think instead of changing it to use the full `Window.availableBounds.height` aka `1.0`
We should make the scroll view use the full height of the Window bounds and make the window move position in relation to view children bounds (heights) and display size (Window.availableBounds.height)
meaning: making the window move with required parameterSection height until condition `(parameterSection.bounds.height + window.bounds.height) > Window.availableBounds.height` is met.
I guess `window.bounds.height` is not really the correct number here? We need _(menubar+border+transportSection+infoSection)_ total height. _**~_

Hmm how to do that? We can get the two first childen — which is our transport- and info section.
```supercollider
if((parameterSection.bounds.height.postln + (window.view.children[0].bounds.height.postln + window.view.children[1].bounds.height.postln).postln) > (Window.availableBounds.height), { ...
```
njaaaeh wrong.. its just the first child bounds.height we need to get correct calculation?
Ah there is probably some convenience method for this on View that I totally missed. TL;DR


_**~_ Aaaand probably here there is some issue with Wayland tiling wm's.

**Comment by salkin-mada** [comment]
woops.. assign no yes no yes no. great github. 🙃

**Comment by redFrik** [comment]
to fix this issue i propose the following changes...
https://github.com/madskjeldgaard/nodeproxygui2/compare/main...redFrik:nodeproxygui2:window-height-scroll
(also takes care of a bug i found - numParams should use flatSize)

**Comment by dietcv** [comment]
thanks alot for all the insight and the proposed solutions :)

**Comment by dietcv** [comment]
I have tried out the suggested solution by @redFrik. The window has been expanded to its fullest with all params available, even beyond the available bounds of the screen and the scroll bar disappeared.

**Comment by salkin-mada** [comment]
Ah okay! Is that intended? — Have you tried #56 ?

To me this sounds as something you don't want :)
> even beyond the available bounds of the screen and the scroll bar disappeared.

**Comment by redFrik** [comment]
many thanks for testing @dietcv 
are you sure it's expanding beyond the screen height?  example code?
i know it might look like it, but i believe that only happens when the position of the GUI window is not at the top.  i.e. in certain circumstances one need to move the GUI window up manually to see all the parameters.
my idea was that the scroll only kicks in when there are more parameters than can fit the screen height - regardless of window position.  but maybe i'm wrong and that's not how it should be?  (or there could be a bug in my PR of course).

**Comment by dietcv** [comment]
Hey, i have tested with a more complex gui, where the gui2 is placed on a different window.
But you can replicate the error, when you first evaluate the Ndef, then run NodeProxyGui2 and then evaluate the Ndef again.

(
Ndef(\test, {
var freqRange = \freqRange.kr(Array.fill(100, {440}), spec: ControlSpec(20, 1000));
});
)
NodeProxyGui2(Ndef(\test));

![grafik](https://github.com/user-attachments/assets/d39d164d-2b3c-4f81-8e2f-2579f314797d)


I guess what was happening with my initial test is that, the gui2 is asynchronously added after the window was already setup, resulting in the incorrect expansion per default. But cant replicate that with the code below, only if you evaluate the Ndef again:

(
Ndef(\test, {
var freqRange = \freqRange.kr(Array.fill(100, {440}), spec: ControlSpec(20, 1000));
});
)

g = NodeProxyGui2(Ndef(\test), show: false);

w = Window(\test, Rect(10, 720, 440, 320)).front;
w.layout = VLayout(VLayout.new(), g);

**Comment by dietcv** [comment]
Okay, i guess this makes it more clear:

n = NodeProxy.audio(s, 100).source_{ \freqRange.kr(Array.fill(100, {440}), spec: ControlSpec(20, 1000)) };
g = NodeProxyGui2(n);
n.source_{ \freqRange.kr(Array.fill(100, {440}), spec: ControlSpec(20, 1000)) };

Is there a change to be made in nodeProxyChanged for \source ?

**Comment by redFrik** [comment]
great examples.  thanks.
i found the problem and reworked my PR.  hope it's better now.
also managed to get rid of that defer call.
the trick was to check parameterSection.sizeHint instead of window.view.sizeHint and also make sure the numParams != params.flatSize optimisation didn't happen for windows with a scroll view.

**Comment by dietcv** [comment]
Thanks so much! In the past i had another issue which was based on exactly that defer i guess. Very awesome that you found a way to get rid of that. I will test the new PR and let you know.

**Comment by dietcv** [comment]
hey, @redFrik. I found a really special edge case: if you place gui2 on a window together with lets say some buttons. But your number of params would initially fit the screen without scrolling (here 28). Then when beeing placed on that same window with the buttons no scrolling takes over and some of the params will be placed beyond the screen:

n = NodeProxy.audio(s, 28).source_{ \freqs.kr(Array.fill(28, {440}), spec: ControlSpec(20, 1000)) };
g = NodeProxyGui2(n, show: false);
b = VLayout(*8.collect{ |i| Button(bounds: 100@20).states_([["button_%".format(i)]]) });
w = Window(\test, Rect(10, 720, 440, 320)).front;
w.layout = VLayout(b, g);

**Comment by redFrik** [comment]
another good example @dietcv .  thanks - keep them coming.
but oh, that was tricky.  had to rethink the whole thing.
i believe i found the solution... there should always be a ScrollView added and resizing should only occur if there's no parent (= not embedded).
so now, in your above example, the gui2 won't try to expand the parent window (much) but instead add itself with a scrollview.  you're responsible for providing enough space when creating the window after the fact.  i think this is the most logical and consistent.
thoughts?

**Comment by dietcv** [comment]
awesome @redFrik. I guess its working perfectly (have adjusted the window, so it perfectly fits my screen when using 8 buttons).

n = NodeProxy.audio(s, 28).source_{ \freqs.kr(Array.fill(28, {440}), spec: ControlSpec(20, 1000)) };
g = NodeProxyGui2(n, show: false);
b = VLayout(*8.collect{ |i| Button(bounds: 100@20).states_([["button_%".format(i)]]) });
w = Window(\test, Rect(10, 60, 440, 980)).front;
w.layout = VLayout(b, g);

n.source_{ \freqs.kr(Array.fill(20, {440}), spec: ControlSpec(20, 1000)) };

**Comment by salkin-mada** [comment]
Merged! closing. Re-open if need be <3

**Comment by redFrik** [comment]
inf.do{thank you}
